import './vendor/OwlCarousel2-2.3.4/dist/owl.carousel.js';
import './vendor/OwlCarousel2-2.3.4/dist/assets/owl.carousel.css';
import './scss/main.scss';
import './js/main.js';
import photo1 from './images/photo-1.jpg';
import note from './images/icons/music-note-1.svg';
import arrow from './images/arrow.png';
import decorate from './images/stroke-2.png';
import headerBG from './images/header-bg.png';
import stroke from './images/stroke.png';
import stroke_3 from './images/stroke-3.png';
import slider_1__wrap from './blocks/slider-1/__wrap/js/slider-1__wrap.js';
import block_bg_2 from './images/2block-bg.png';
import stroke_4 from './images/stroke-4.png';
import photo_5 from './images/photo-5.jpg';
import photo_4 from './images/photo-4.jpg';
import photo_7 from './images/photo-7.jpg';
import photo_6 from './images/photo-6.jpg';
import block_bg_3 from './images/3block-bg.png';
import stroke_6 from './images/stroke-6.png';
import block_bg_4 from './images/4block-bg.png';
import photo_8 from './images/photo-8.jpg';
import photo_10 from './images/photo-10.jpg';
import photo_11 from './images/photo-11.jpg';
import slider_2__wrap from './blocks/slider-2/__wrap/js/slider-2__wrap.js';